In [88]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [89]:
df_user = pd.read_csv('Retail domain books\BX-Users.csv',encoding='latin-1')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [90]:
df_books = pd.read_csv('Retail domain books\BX-Books.csv',encoding='latin-1')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [91]:
df = pd.read_csv('Retail domain books\BX-Book-Ratings.csv',encoding='latin-1', nrows=10000)

In [92]:
df_user.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [93]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [94]:
df.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [95]:
df= pd.merge(df,df_books, on='isbn')

In [96]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

In [97]:
n_users = df['user_id'].nunique()
n_users

828

In [98]:
n_isbn = df.isbn.nunique()
n_isbn

8051

In [99]:
isbn_list = df.isbn.unique()
len(isbn_list)

8051

In [100]:
def assign_isbn_index(isbn):
    itemindex = np.where(isbn_list==isbn)
    return itemindex[0][0]

In [101]:
assign_isbn_index('446520802') #test

2

In [102]:
user_list = df.user_id.unique()

In [103]:
def assign_user_index(userid):
    itemindex = np.where(user_list == userid)
    return itemindex[0][0]

In [104]:
assign_user_index(276725)

0

In [105]:
df['user_index'] = df.user_id.apply(assign_user_index)

In [106]:
df['isbn_index'] = df.isbn.apply(assign_isbn_index)

In [108]:
df.head(5)

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  user_index  isbn_index  
0                2002            Ballantine Books           0           0  
1                2001                      Heinle           1           1  
2                1996                Warner Books           2           2  
3                1996                Warner Books           3           2  
4                1999  Cambridge University Press           4           3

In [109]:
from sklearn.model_selection import train_test_split

In [110]:
train_data, test_data = train_test_split(df, test_size=0.25)

In [111]:
train_data.shape

(6525, 9)

In [112]:
test_data.shape

(2176, 9)

In [114]:
train_data_matrix = np.zeros((n_users,n_isbn))

In [115]:
test_data_matrix = np.zeros((n_users,n_isbn)) 

In [126]:
for item in train_data.itertuples():
    print(item)
    print(item[3])
    print(str(item[8]))
    print("isbn_index: ",str(item[9]))
    break

Pandas(Index=3213, user_id=277984, isbn='345384369', rating=0, book_title='Intensity', book_author='DEAN KOONTZ', year_of_publication='1996', publisher='Ballantine Books', user_index=533, isbn_index=2688)
0
533
isbn_index:  2688


In [127]:
for item in train_data.itertuples():
    train_data_matrix[item[8]-1, item[9]-1] = item[3]

In [128]:
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [129]:
for item in test_data.itertuples():
    test_data_matrix[item[8]-1, item[9]-1] = item[3]

In [130]:
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [131]:
from sklearn.metrics.pairwise import pairwise_distances

In [133]:
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')

In [134]:
user_similarity.shape

(828, 828)

In [135]:
item_similarity.shape

(8051, 8051)

In [136]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [137]:
item_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [138]:
#pediction
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis]) 
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])     
    return pred

In [139]:
user_prediction = predict(train_data_matrix, user_similarity, 'user')

In [143]:
item_prediction = predict(train_data_matrix, item_similarity, 'item')

In [145]:
user_prediction

array([[-0.00126146, -0.00126146,  0.00236611, ...,  0.00962125,
        -0.00126146, -0.00126146],
       [ 0.0041627 , -0.00188325,  0.00174432, ...,  0.00899946,
        -0.00188325, -0.00188325],
       [ 0.06435308,  0.0583061 ,  0.06193429, ...,  0.06919067,
         0.0583061 ,  0.0583061 ],
       ...,
       [ 0.0041627 , -0.00188325,  0.00174432, ...,  0.00899946,
        -0.00188325, -0.00188325],
       [ 0.0041627 , -0.00188325,  0.00174432, ...,  0.00899946,
        -0.00188325, -0.00188325],
       [ 0.0041627 , -0.00188325,  0.00174432, ...,  0.00899946,
        -0.00188325, -0.00188325]])

In [146]:
item_prediction

array([[0.        , 0.00062112, 0.00062112, ..., 0.0006217 , 0.00062112,
        0.00062112],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06012422, 0.06012422, 0.06012422, ..., 0.06018089, 0.06012422,
        0.06012422],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [141]:
#calculare accuracy of the model

In [147]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [148]:
#please explain rmse?
def rmse(prediction, actual):
    prediction = 

SyntaxError: invalid syntax (<ipython-input-148-0f6cff2c78aa>, line 1)

In [ ]:
# how to get the recommended values?