In [33]:
import numpy as np

In [34]:
R = np.matrix([[-1,-1,-1,-1,0,-1],[-1,-1,-1,0,-1,100],[-1,-1,-1,0,-1,-1],[-1,0,0,-1,0,-1],[0,-1,-1,0,-1,100],[-1,0,-1,-1,0,100]])

In [35]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [36]:
Q=np.matrix(np.zeros([6,6]))

In [37]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [38]:
gamma=0.8

In [39]:
initial_state=1

In [40]:
def available_actions(state):
    current_state_row = R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [41]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [42]:
available_act = available_actions(initial_state)

In [43]:
available_act

array([3, 5], dtype=int64)

In [44]:
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_actions_range,1))
    return next_action

In [45]:
action=sample_next_action(available_act)
print(action)

3


In [46]:
R[1,]

matrix([[ -1,  -1,  -1,   0,  -1, 100]])

In [47]:
np.max(R[1,])

100

In [48]:
def update(current_state, action, gamma):
    max_value = np.max(Q[action,])
    Q[current_state, action]=R[current_state, action]+gamma*max_value

In [49]:
update(initial_state, action, gamma)

In [50]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [51]:
for i in range(10000):
    current_state=np.random.randint(0,6)
    available_act = available_actions(current_state)
    action=sample_next_action(available_act)
    update(current_state, action, gamma)
    print(Q)
    var=input("give input")

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
give input2
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
give input3
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
give input4
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
give input3
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   

KeyboardInterrupt: 

In [32]:
Q/5

matrix([[  0. ,   0. ,   0. ,   0. ,  80. ,   0. ],
        [  0. ,   0. ,   0. ,  64. ,   0. , 100. ],
        [  0. ,   0. ,   0. ,  64. ,   0. ,   0. ],
        [  0. ,  80. ,  51.2,   0. ,  80. ,   0. ],
        [ 64. ,   0. ,   0. ,  64. ,   0. , 100. ],
        [  0. ,  80. ,   0. ,   0. ,  80. , 100. ]])

In [29]:
current_state=2
steps=[current_state]
while current_state!=5:
    next_step_index = np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index = np.random.choice(next_step_index,size=1)
    next_step_index=int(next_step_index)
    steps.append(next_step_index)
    current_state=next_step_index

In [30]:
steps

[2, 3, 1, 5]